-- FORD 32
USE Ford32_school;

-- Procedure
DELIMITER //
	CREATE PROCEDURE insert_alum_tut(IN al_nombre VARCHAR(200), al_curp VARCHAR(25), tu_nombre VARCHAR(200), grupo INT, sexo VARCHAR(10), pes DOUBLE, tall DOUBLE)
    BEGIN
		-- Obtener el numero de registro de alumnos
		SET @num_id = ((SELECT COUNT(idAlumno) FROM Alumnos) + 1);
        
		-- Obtener la fecha de nacimiento
		SET @str_fecnac = (SELECT SUBSTRING(al_curp, 5, 6));
		SET @str_fecnac_sep = (SELECT CONCAT(SUBSTRING(@str_fecnac, 5, 4), '-', SUBSTRING(@str_fecnac, 3, 2), '-', SUBSTRING(@str_fecnac, 1, 2)));
		SET @fec_nac = (SELECT STR_TO_DATE(@str_fecnac_sep, '%d-%m-%Y'));
        
        -- Obtener el nombre y los apellidos del tutor
		SET @length_tutor = (SELECT CHAR_LENGTH(tu_nombre));
		SET @pos_first_empty_tu = (SELECT POSITION(' ' IN tu_nombre));
		SET @pos_finally_empty_tu = (SELECT LOCATE (' ', tu_nombre, (@pos_first_empty_tu +1)));
		SET @apellidos_tu = (SELECT SUBSTRING(tu_nombre, 1, @pos_finally_empty_tu-1));
        
        SET @length_tu_ape = (SELECT CHAR_LENGTH(@apellidos_tu));
		SET @pos_first_empty_tu_ape = (SELECT POSITION(' ' IN @apellidos_tu));
        SET @ape_pat_tu = (SELECT SUBSTRING(@apellidos_tu, 1, @pos_first_empty_tu_ape-1));
        SET @ape_mat_tu = (SELECT SUBSTRING(@apellidos_tu, @pos_first_empty_tu_ape + 1, @length_tu_ape-1));

        SET @nombre_tu = (SELECT SUBSTRING(tu_nombre, @pos_finally_empty_tu+1, @length_tutor));
        
		-- Obtener el nombre y apellidos del alumno
        SET @length_alumno = (SELECT CHAR_LENGTH(al_nombre));
		SET @pos_first_empty_al = (SELECT POSITION(' ' IN al_nombre));
		SET @pos_finally_empty_al = (SELECT LOCATE (' ', al_nombre, (@pos_first_empty_al +1)));
		SET @apellidos_al = (SELECT SUBSTRING(al_nombre, 1, @pos_finally_empty_al-1));
        
		SET @length_al_ape = (SELECT CHAR_LENGTH(@apellidos_al));
		SET @pos_first_empty_al_ape = (SELECT POSITION(' ' IN @apellidos_al));
        SET @ape_pat_al = (SELECT SUBSTRING(@apellidos_al, 1, @pos_first_empty_al_ape-1));
        SET @ape_mat_al = (SELECT SUBSTRING(@apellidos_al, @pos_first_empty_al_ape + 1, @length_al_ape-1));
        
		SET @nombre_al = (SELECT SUBSTRING(al_nombre, @pos_finally_empty_al+1, @length_al_ape));

        -- SELECT @nombre_al, @ape_pat_al, @ape_mat_al, @nombre_tu, @ape_pat_tu, @ape_mat_tu, @fec_nac, @num_id, al_curp;

        -- INSERT ALUMNO
		INSERT INTO Alumnos (idAlumno, nombre, ape_paterno, ape_materno, fec_nacimiento, sexo, curp, fk_grupo)
			VALUES (@num_id, @nombre_al,  @ape_pat_al, @ape_mat_al,  @fec_nac, sexo, al_curp, grupo);
            
		-- INSERT TUTOR
        INSERT INTO Tutores(idTutor, nombre, ape_paterno, ape_materno) VALUES (@num_id, @nombre_tu,  @ape_pat_tu, @ape_mat_tu);
            
		-- ACTUALIZACION DEL ALUMNO
        UPDATE Alumnos SET fk_tutor = @num_id, fk_dato_alumno = @num_id WHERE idAlumno = @num_id;
        
        -- ACTUALIZAR EL PESO Y LA TALLA DE LOS ALUMNOS
        UPDATE DatosAlumno SET peso = pes, talla = tall WHERE idDatoAlumno = @num_id;
    END //
DELIMITER ;

-- Consultas
SELECT * FROM Alumnos;
SELECT * FROM Tutores;
SELECT * FROM DatosAlumno;

-- INSERT INTO Alumnos (idAlumno, nombre, apellidos, fec_nacimiento, sexo, curp, fk_grupo) VALUES (1, 'GERARDO DE JESUS', 'BANDALA VALENCIA ', '2013-12-08', 'M', 'BAVG131208HVZNLRA2', 1);

-- 1er año
CALL insert_alum_tut('BANDALA VALENCIA GERARDO DE JESUS', 'BAVG131208HVZNLRA2', 'VALENCIA CRUZ GUILLERMINA', 1, 'M', 23, 1.14);
CALL insert_alum_tut('BASILIO VAZQUEZ BRAIYAN DE JESUS', 'BAVB130409HVZSZRA8', 'VAZQUEZ ALVAREZ NORMA LETICIA', 1, 'M', 19.5, 1.15);
CALL insert_alum_tut('BASTIAN DE LOS SANTOS JONATHAN GEOVANNI', 'BASJ130513HVZSNHA4', 'BASTIAN VASQUEZ CELINA', 1, 'M', 21, 1.10);
CALL insert_alum_tut('BECERRA ROSADO KITZIA NAHOMI', 'BERK130411MVZCSTA8', 'ROSADO MONTERO NAYANIT', 1, 'F', 0, 0);
CALL insert_alum_tut('CANCINO ESTRADA LUIS ABEL', 'CAEL130607HVZNSSA9', 'CANCINO ESTRADA ESTELA ZULEIMA', 1, 'M', 22, 1.16);
CALL insert_alum_tut('GALINDO CASTRO CARLOS EDUARDO', 'GACC130627HVZLSRA7', 'IZQUIERDO CLEMENTE MARGARITA', 1, 'M', 22, 1.18);
CALL insert_alum_tut('GARCÍA RODRÍGUEZ OSMAR GANEN', 'GARO130531HVZRDSA7', 'BOCARANDO RODRIGUEZ MARIA DE LOURDES', 1, 'M', 17, 1.11);
CALL insert_alum_tut('HERNÁNDEZ SANTES ARNULFO', 'HESA130118HVZRNRA4', 'SANTES VAZQUEZ FRANCISCA', 1, 'M', 20, 1.14);
CALL insert_alum_tut('MELGAREJO JERÓNIMO JESÚS ALBERTO', 'MEJJ130422HVZLRSA2', 'GERONIMO PARRAL JASMIN', 1, 'M', 25.5, 1.13);
CALL insert_alum_tut('OLMEDO VICENTE KARLA DAYREN', 'OEVK130714MVZLCRA1', 'OLMEDO GARCÍA VICTOR HUGO', 1, 'F', 18, 1.07);
CALL insert_alum_tut('QUIROZ SANTES ESTEFANÍA', 'QUSE130117MVZNRSA1', 'SANTES VAZQUEZ FRANCISCA', 1, 'F', 21, 1.17);
CALL insert_alum_tut('SALINAS PERDOMO DAYANA GUADALUPE', 'SAPD130205MVZLRYA9', 'PERDOMO GARCÍA VIVIANA', 1, 'F', 34, 1.22);
CALL insert_alum_tut('SANTIAGO LOPEZ EMMANUEL', 'SALE131207HVZNPMA1', 'SANTIAGO LOPEZ MARIA GUADALUPE', 1, 'M', 0, 0);
CALL insert_alum_tut('SIMBRON AVELINO MARISOL', 'SIAM130105MVZMVRA5', 'AVELINO GARCÍA MARÍA DE LOS ANGELES', 1, 'F', 27, 1.13);

-- SEGUNDO
CALL insert_alum_tut('AGUILAR SANTES FATIMA CLARET', 'AUSF120527MVZGNTA8', 'SANTES RODRIGUEZ BRIANDA', '3', 'F', '24', '1.25');
CALL insert_alum_tut('BANDALA SEBASTIAN LEONARDO ALBERTO', 'BASL120112HVZNBNA0', 'SEBASTIAN VARGAS MERCY JARETTE', '3', 'M', '23', '1.20');
CALL insert_alum_tut('CANCINO ESTRADA YAZMIN ABRIL', 'CAEY120405MVZNSZA1', 'ESTRADA PEREZ MARIA GUADALUPE', '3', 'F', '0', '0');
CALL insert_alum_tut('CRUZ HERNANDEZ EDUARDO', 'CUHE120215HVZRRDA1', 'ANDRADE JUAREZ JUDITH', '3', 'M', '32', '1.25');
CALL insert_alum_tut('LOPEZ ALARCON CIELO LISSET', 'LOAC121222MVZPLLA2', 'LOPEZ ALARCON NOELIA YADIRA', '3', 'F', '18', '1.15');
CALL insert_alum_tut('RUIZ SIMBRON TERESA YAMILETH', 'RUST120905MVZZMRA3', 'SIMBRON TEJADA IRENE', '3', 'F', '19', '1.18');
CALL insert_alum_tut('SAAVEDRA TEJADA ZURIA MELISA', 'SATZ120516MVZVJRA3', 'TEJADA SANTES EDITH', '3', 'F', '29.5', '1.16');
CALL insert_alum_tut('SALAS MALDONADO YIREH', 'SAMY121207HVZLLRA5', 'MALDONADO VIDAL OFELIA', '3', 'M', '19.5', '1.17');
CALL insert_alum_tut('SOSA GARCIA ANGELICA', 'SOGA120511MVZSRNA1', 'SOSA GARCÍA OFELIA', '3', 'F', '20', '1.16');
CALL insert_alum_tut('VILLA HERNÁNDEZ HEIDI BETSABE', 'VIHH120517MVZLRDA1', 'HERNANDEZ PEREZ ERIKA', '3', 'F', '27.5', '1.21');
CALL insert_alum_tut('VIVEROS RIVERA JEFTE ESTEBAN', 'VIRJ120820HVZVVFA8', 'RIVERA NAVA KEREN', '3', 'M', '39', '1.28');

-- TERCERO
CALL insert_alum_tut('BASTIAN DE LOS SANTOS AXEL', 'BASA110717HVZSNXA6', 'BASTIAN VAZQUEZ CELINA', '5', 'M', '0', '0');
CALL insert_alum_tut('CABRERA RODRIGUEZ OSVALDO ODARBIL', 'CARO111008HVZBDSA0', 'RODRIGUEZ GUZMAN MARIA DEL ROSARIO', '5', 'M', '0', '0');
CALL insert_alum_tut('DORANTES MENDEZ JONATHAN URIEL', 'DOMJ110921HVZRNNA2', 'MENDEZ MORGADO MARIA MAGDALENA', '5', 'M', '0', '0');
CALL insert_alum_tut('GARCIA GOMEZ EBER NATANAEL', 'GAGE110815HVZRMBA9', 'GARCÍA BALDERRABANO MARIELA', '5', 'M', '0', '0');
CALL insert_alum_tut('HERNANDEZ GARCIA JOSE IGNACIO', 'HEGI111014HVZRRGA9', 'GARCÍA GARCÍA CECILIA', '5', 'M', '0', '0');
CALL insert_alum_tut('HERNANDEZ TEJADA GUSTAVO YAHIR', 'HETG101101HVZRJSA1', 'TEJADA LARIOS ARACELI', '5', 'M', '0', '0');
CALL insert_alum_tut('MENDEZ SALAS JONATHAN JONAS', 'MESJ111101HVZNLNA4', 'SALAS DE LA CRUZ OLGA BEATRIZ', '5', 'M', '0', '0');
CALL insert_alum_tut('NICANOR PACHECO CRISTIAN ALEXIS ', 'NIPC111114HPLCCRA2', 'PACHECO VÁZQUEZ  CLAUDIA IVETH ', '5', 'M', '0', '0');
CALL insert_alum_tut('OLMEDO GRANADOS DANARELI', 'OEGD111124MVZLRNA3', 'GRANADOS BAUTISTA ANA KARINA', '5', 'F', '0', '0');
CALL insert_alum_tut('PEREZ REYES ALEXIS MICHELLE', 'PERA111107HVZRYLA4', 'REYES PEREZ CHANTAL', '5', 'M', '0', '0');
CALL insert_alum_tut('REYES QUIROZ RODRIGO DE JESUS', 'REQR111207HVZYRDA0', 'QUIROZ LOPEZ MARIA ANTONIETA', '5', 'M', '0', '0');
CALL insert_alum_tut('SALAS DE LA CRUZ ANGEL ALFREDO', 'SACA110326HVZLRNA0', 'SALAS RODRIGUEZ GUSTAVO', '5', 'M', '0', '0');

-- CUARTO A
CALL insert_alum_tut('CAMPOS ORTEGA STORMIE DANIELA', 'CAOS100210MVZMRTA5', 'ORTEGA BERNABE ISABEL', '7', 'F', '0', '0');
CALL insert_alum_tut('CANCINO ESTRADA ANDREA ROCIO', 'CAEA101008MVZNSNA6', 'CANCINO ESTRADA ESTELA ZULEIMA', '7', 'F', '0', '0');
CALL insert_alum_tut('DORANTES MENDEZ JULIO CESAR', 'DOMJ100718HVZRNLA0', 'MENDEZ MORGADO MARIA MAGDALENA ', '7', 'M', '0', '0');
CALL insert_alum_tut('GARCIA HERNANDEZ CESAR', 'GAHC100209HVZRRSA8', 'GARCIA GARCIA VERONICA ELENA ', '7', 'M', '0', '0');
CALL insert_alum_tut('GARCIA HERNANDEZ LAURA SARAHI', 'GAHL100323MVZRRRA9', 'HERNANDEZ JUAREZ VIRGINIA', '7', 'F', '0', '0');
CALL insert_alum_tut('GARCIA RODRIGUEZ AXEL VIDAL', 'GARA101204HVZRDXA0', 'RODRIGUEZ BOCARANDO MARIA DE LOURDES', '7', 'M', '0', '0');
CALL insert_alum_tut('GONZALEZ OLMOS SANDRA YOSELIN', 'GOOS100413MVZNLNA3', 'OLMOS HERNANDEZ VALENTINA', '7', 'F', '0', '0');
CALL insert_alum_tut('GUZMAN GONZALEZ GIOVANI', 'GUGG100331HVZZNVA9', 'GUZMAN GONZALES BEATRIZ', '7', 'M', '0', '0');
CALL insert_alum_tut('HERNANDEZ CRUZ PEDRO', 'HECP100721HTSRRDA3', 'CRUZ BAUTISTA YASMIN', '7', 'M', '0', '0');
CALL insert_alum_tut('MARTINEZ CARREON LUZ YAERLI', 'MACL100407MVZRRZA0', 'CARREON MARTINEZ MARGARITA', '7', 'F', '0', '0');
CALL insert_alum_tut('PALAGOT VALENCIA YAMILETH', 'PAVY091128MTSLLMA8', 'VALENCIA GARCIA ERIKA ANAHI', '7', 'F', '0', '0');
CALL insert_alum_tut('QUIROZ SANTES JOSE ARMANDO', 'QUSA100924HVZRNRA2', 'SANTES VAZQUES FRANCISCA', '7', 'M', '0', '0');
CALL insert_alum_tut('SAAVEDRA TEJADA JESUS ALFREDO', 'SATJ100124HVZVJSA3', 'TEJADA SANTES EDITH', '7', 'M', '0', '0');
CALL insert_alum_tut('SOTO TEJADA ABRIL DEL CARMEN', 'SOTA100316MVZTJBA7', 'TEJADA VAZQUES MARIA DEL CARMEN', '7', 'F', '0', '0');

-- CUARTO B
CALL insert_alum_tut('CRUZ BAUTISTA GAEL GUADALUPE', 'CUBG101212HVZRTLA6', 'CRUZ BAUTIZTA LAURA AREMI', '8', 'M', '0', '0');
CALL insert_alum_tut('DE LOS SANTOS MARTINEZ JOSE ANGEL', 'SAMA101005HTSNRNA9', 'DE LOS SANTOS MONTOYA ISRAEL', '8', 'M', '0', '0');
CALL insert_alum_tut('HERNANDEZ TEJADA LUCERO YANET', 'HETL090516MVZRJCA7', 'TEJADA LARIOS ARACELY', '8', 'F', '0', '0');
CALL insert_alum_tut('MALPICA MELGAREJO CLAUDIA HARUMI', 'MAMC101116MVZLLLA3', 'MALPICA FRANCISCO CLAUDIO', '8', 'F', '0', '0');
CALL insert_alum_tut('PEREZ OLMOS MIGUEL ANGEL', 'PEOM091003HVZRLG0', 'GOMEZ PEREZ CECILIA', '8', 'M', '0', '0');
CALL insert_alum_tut('SANTIAGO FERNANDEZ EDITH GUADALUPE', 'SAFE101106MTSNRDA1', 'FERNANDEZ RAMIREZ MARÍA GUADALUPE', '8', 'F', '0', '0');
CALL insert_alum_tut('SIMBRON GONZALEZ ESTEBAN', 'SIGE091126HVZMNSA7', 'GONZALES CORTEZ ELSA', '8', 'M', '0', '0');
CALL insert_alum_tut('VILLEGAS MELGAREJO JUSTIN TIMBERLAKE', 'VIMJ100123MTSLLSA3', 'MELGAREJO GARCÍA JUAN CARLOS', '8', 'F', '0', '0');
CALL insert_alum_tut('ZALETAS LOPEZ ITZEL GUADALUPE', 'ZALI100607MVZLPTA8', 'LOPEZ FRANCISO LILIANA', '8', 'F', '0', '0');

-- QUINTO
CALL insert_alum_tut('ALDAZ RIVERA VALERIA YAZMIN', 'AARV091125MVZLVLA5', 'MARIA PEREZ MARIA ELISA', '9', 'F', '0', '0');
CALL insert_alum_tut('ALVARADO GARCIA JESUS ADOLFO', 'AAGJ090908HSLLRSA2', 'GARCÍA GUERRA MARISOL', '9', 'M', '0', '0');
CALL insert_alum_tut('BANDALA SEBASTIAN JORGE ALEXEI', 'BASJ090204HVZNBRA9', 'SEBASTIAN VARGAS MERCY JARETTE', '9', 'M', '0', '0');
CALL insert_alum_tut('BASTIAN DE LOS SANTOS JOSUE RICARDO', 'BASJ090824HTSSNSA8', 'BASTIAN VAZQUEZ CELINA', '9', 'M', '0', '0');
CALL insert_alum_tut('CONTRERAS GONZALES SAMUEL ALEJANDRO', 'COGS090819HTSNNMA9', 'GONZALES VAZQUEZ ROSALIA', '9', 'M', '0', '0');
CALL insert_alum_tut('CORONA HERNANDEZ ANA KAREN', 'COHA091218MVZRRNA7', 'HERNANDEZ GARCIA LILIA', '9', 'F', '0', '0');
CALL insert_alum_tut('CRUZ BAUTISTA ROXANA YAMILETH', 'CUBR080504MVZRTXA8', 'CRUZ BAUTISTA YASMIN', '9', 'F', '0', '0');
CALL insert_alum_tut('GARCIA CASTILLO ROSARIO', 'GACR090114MVZRSSA7', 'CASTILLO LEAL OLGA GUADALUPE', '9', 'F', '0', '0');
CALL insert_alum_tut('GARCIA GOMEZ AXEL ABRAHAM', 'GAGA090810HVZRMXA5', 'GARCIA BALDERABANO MARIELA', '9', 'M', '0', '0');
CALL insert_alum_tut('HERNANDEZ ORTIZ HECTOR HUGO', 'HEOH090201HVZRRCA9', 'HERNANDEZ GANDARA JOSE LUIS', '9', 'M', '0', '0');
CALL insert_alum_tut('HERNANDEZ SANTES EDUARDO', 'HESE071008HVZRNDA0', 'SANTES VAZQUEZ FRANCISCA', '9', 'M', '0', '0');
CALL insert_alum_tut('MENDEZ CAMPOS YISSEL VICTORIA', 'MECY090211MVZNMSA5', 'CAMPOS NUÑES ERIKA', '9', 'F', '0', '0');
CALL insert_alum_tut('PALAGOT VALENCIA JOAN ALEXANDER', 'PAVJ081020HTSLLNA1', 'VALENCIA GARCIA ERIKA ANAHI', '9', 'M', '0', '0');
CALL insert_alum_tut('PASCUAL GARCIA ANGELI MICHELLE', 'PAGA090719MVZSRNA9', 'GARCIA SOSA SELENA', '9', 'F', '0', '0');
CALL insert_alum_tut('PEREZ GARCIA DULCE VIVIANA', 'PEGD091202MVZRRLA3', 'GAONA JIMENEZ ENRIQUETA', '9', 'F', '0', '0');
CALL insert_alum_tut('PEREZ OLMEDO GABRIEL AMAURY', 'PEOG090715HTSRLBA8', 'OLMEDO GARCIA AMY VICTORIA', '9', 'M', '0', '0');
CALL insert_alum_tut('RAMOS GARCIA  GIOVANNI', 'RAGG090912HVZMRVA2', 'GARCIA HERNANDEZ ANA KAREN', '9', 'M', '0', '0');

-- SEXTO
CALL insert_alum_tut('BAUTISTA VALENCIA LUIS URIEL', 'BAVL080315HVZTLSA6', 'VALENCIA RAMIREZ MAURA', '11', 'M', '0', '0');
CALL insert_alum_tut('CORONA HERNANDEZ JUAN ANTONIO', 'COHJ081215HVZRRNA2', 'HERNANDEZ GARCIA LILIA', '11', 'M', '0', '0');
CALL insert_alum_tut('GUZMAN GONZALEZ BLADIMIR', 'GUGB081210HVZZNLA5', 'GUZMAN GONZALES BEATRIZ', '11', 'M', '0', '0');
CALL insert_alum_tut('HERNANDEZ GARCIA PALOMA ZURISADAY', 'HEGP081125MVZRRLA7', 'GARCIA BALDERABANO MARIELA', '11', 'F', '0', '0');
CALL insert_alum_tut('HERNANDEZ SANTES ALBERTO', 'HESA060721HVZRNLA7', 'SANTES VAZQUEZ FRANCISCA', '11', 'M', '0', '0');
CALL insert_alum_tut('HERRERA SANTES LISANDRO', 'HESL080712HVZRNSA3', 'SANTES OLARTE LETICIA', '11', 'M', '0', '0');
CALL insert_alum_tut('JAIMEZ GARCIA FATIMA NEMITZEL', 'JAGF071121MVZMRTA6', 'GARCIA MAYA DULCE MALENA', '11', 'F', '0', '0');
CALL insert_alum_tut('OLMEDO GRANADOS KEYDI ANALY', 'OEGK080930MHGLRYA0', 'GRANADOS BAUTISTA ANA KARINA', '11', 'F', '0', '0');
CALL insert_alum_tut('PEREZ GARCIA KARLA GUADALUPE', 'PEGK081212MVZRRRA0', 'GAONA JIMENEZ ENRIQUETA', '11', 'F', '0', '0');
CALL insert_alum_tut('PEREZ SETIEN ALEXIA', 'PESA081114MDFRTLA7', 'SETIEN VAZQUEZ HORTENCIA', '11', 'F', '0', '0');
CALL insert_alum_tut('RAMIREZ CRUZ ADELA', 'RACA080921MTSMRDA1', 'CRUZ QUINTANA ALMA DELIA', '11', 'F', '0', '0');
CALL insert_alum_tut('SALAS TRUJILLO ESTANIS ALFREDO', 'SATE080109HTSLRSA8', 'TRUJILLO BALDERABANO ALDA LINDA', '11', 'M', '0', '0');
CALL insert_alum_tut('SANTES BENAVIDES FRIDA YARETZI', 'SABF080430MDFNNRA', 'BENAVIDES PEREZ GRACIELA ', '11', 'F', '0', '0');
CALL insert_alum_tut('SANTIAGO FERNANDEZ MARDONIO', 'SAFM081220HTSNRRA9', 'FERNANDEZ RAMIREZ MARIA GUADALUPE', '11', 'M', '0', '0');
CALL insert_alum_tut('VALENCIA PEREZ ESTEBAN', 'VAPE081017HVZLSRA9', 'PEREZ GARCIA TERESA', '11', 'M', '0', '0');
CALL insert_alum_tut('VEGA ORTIZ NOEMI', 'VEON080503MVZGRMA1', 'ORTIZ GARCIA JOSE', '11', 'F', '0', '0');



