-- MySQL Script generated by MySQL Workbench
-- Wed Oct 16 09:54:45 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema ford32_school
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ford32_school
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ford32_school` DEFAULT CHARACTER SET utf8 ;
USE `ford32_school` ;

-- -----------------------------------------------------
-- Table `ford32_school`.`datosalumno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ford32_school`.`datosalumno` (
  `idDatoAlumno` INT(11) NOT NULL,
  `peso` DOUBLE NULL DEFAULT NULL,
  `talla` DOUBLE NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `update_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`idDatoAlumno`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ford32_school`.`grupos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ford32_school`.`grupos` (
  `idGrupo` INT(11) NOT NULL AUTO_INCREMENT,
  `grado` INT(11) NOT NULL,
  `grupo` VARCHAR(2) NOT NULL,
  `activo` ENUM('0', '1') NOT NULL DEFAULT '0',
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `update_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`idGrupo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ford32_school`.`estados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ford32_school`.`estados` (
  `idEstado` INT(11) NOT NULL AUTO_INCREMENT,
  `clave` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `abreviatura` VARCHAR(10) NOT NULL,
  `renapo` VARCHAR(2) NOT NULL,
  PRIMARY KEY (`idEstado`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ford32_school`.`municipios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ford32_school`.`municipios` (
  `idMunicipio` INT(11) NOT NULL AUTO_INCREMENT,
  `fk_estado` INT(11) NOT NULL,
  `clave` VARCHAR(3) NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idMunicipio`),
  INDEX `fk_estado` (`fk_estado` ASC),
  CONSTRAINT `fk_estado`
    FOREIGN KEY (`fk_estado`)
    REFERENCES `ford32_school`.`estados` (`idEstado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ford32_school`.`tipossangre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ford32_school`.`tipossangre` (
  `idTiposSangre` INT(11) NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NOT NULL,
  `simbologia` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTiposSangre`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ford32_school`.`tutores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ford32_school`.`tutores` (
  `idTutor` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `ape_paterno` VARCHAR(100) NULL DEFAULT NULL,
  `ape_materno` VARCHAR(100) NULL DEFAULT NULL,
  `fec_nacimiento` DATE NULL DEFAULT NULL,
  `sexo` ENUM('M', 'F') NULL,
  `domicilio` VARCHAR(200) NULL DEFAULT NULL,
  `telefono` VARCHAR(15) NULL DEFAULT NULL,
  `celular` VARCHAR(15) NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `update_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`idTutor`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ford32_school`.`alumnos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ford32_school`.`alumnos` (
  `idAlumno` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NULL,
    `ape_paterno` VARCHAR(100) NULL DEFAULT NULL,
  `ape_materno` VARCHAR(100) NULL DEFAULT NULL,
  `activo` ENUM('0', '1') NULL DEFAULT '1',
  `fec_nacimiento` DATE NULL,
  `sexo` ENUM('M', 'F') NULL,
  `curp` VARCHAR(20) NULL,
  `fk_lugar_nacimiento` INT(11) NULL,
  `fk_tutor` BIGINT(20) NULL,
  `fk_dato_alumno` INT(11) NULL,
  `fk_tipo_sangre` INT(11) NULL,
  `fk_grupo` INT(11) NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `update_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`idAlumno`),
  INDEX `fk_tipo_sangre` (`fk_tipo_sangre` ASC),
  INDEX `fk_dato_alumno` (`fk_dato_alumno` ASC),
  INDEX `fk_lugar_nacimiento_idx` (`fk_lugar_nacimiento` ASC),
  INDEX `fk_tutor` (`fk_tutor` ASC),
  INDEX `fk_grupo` (`fk_grupo` ASC),
  CONSTRAINT `fk_dato_alumno`
    FOREIGN KEY (`fk_dato_alumno`)
    REFERENCES `ford32_school`.`datosalumno` (`idDatoAlumno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_grupo`
    FOREIGN KEY (`fk_grupo`)
    REFERENCES `ford32_school`.`grupos` (`idGrupo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lugar_nacimiento`
    FOREIGN KEY (`fk_lugar_nacimiento`)
    REFERENCES `ford32_school`.`municipios` (`idMunicipio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tipos_sangre`
    FOREIGN KEY (`fk_tipo_sangre`)
    REFERENCES `ford32_school`.`tipossangre` (`idTiposSangre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tutor`
    FOREIGN KEY (`fk_tutor`)
    REFERENCES `ford32_school`.`tutores` (`idTutor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ford32_school`.`docentes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ford32_school`.`docentes` (
  `idDocente` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `ape_paterno` VARCHAR(100) NULL DEFAULT NULL,
  `ape_materno` VARCHAR(100) NULL DEFAULT NULL,
  `puesto` VARCHAR(45) NOT NULL DEFAULT 'Docente',
  `sexo` ENUM('M', 'F') NULL,
  `activo` ENUM('0', '1') NOT NULL DEFAULT '0',
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `update_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`idDocente`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ford32_school`.`docgrup`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ford32_school`.`docgrup` (
  `idDocGrup` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `fk_docente` INT(11) NOT NULL,
  `fkd_grupo` INT(11) NOT NULL,
  `ciclo_escolar` VARCHAR(45) NOT NULL,
  `activo` ENUM('0', '1') NOT NULL DEFAULT '0',
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `update_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`idDocGrup`),
  INDEX `fk_docente` (`fk_docente` ASC),
  INDEX `fkd_grupo` (`fkd_grupo` ASC),
  CONSTRAINT `fk_docente`
    FOREIGN KEY (`fk_docente`)
    REFERENCES `ford32_school`.`docentes` (`idDocente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fkd_grupo`
    FOREIGN KEY (`fkd_grupo`)
    REFERENCES `ford32_school`.`grupos` (`idGrupo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

-- USE `ford32_school`;
-- DELIMITER $$
-- USE `ford32_school`$$
-- CREATE
-- DEFINER=`root`@`localhost`
-- TRIGGER `ford32_school`.`Alumnos_Create_DatoAlumno`
-- AFTER INSERT ON `ford32_school`.`alumnos`
-- FOR EACH ROW
-- BEGIN
	-- INSERT INTO DatosAlumno(idDatoAlumno, peso, talla) VALUES(NEW.idAlumno, 0.0, 0.0);
-- END$$
-- DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
